[project]
name = "embeddb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=22.3.0",
    "flake8>=4.0.1",
    "isort>=5.10.1",
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "sentence-transformers>=2.0.0",
]
